//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.iPaiWebServiceSoap")]
    public interface iPaiWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xmlString 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        demo.ServiceReference1.GetTokenResponse GetToken(demo.ServiceReference1.GetTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<demo.ServiceReference1.GetTokenResponse> GetTokenAsync(demo.ServiceReference1.GetTokenRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 jsonString 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBill", ReplyAction="*")]
        demo.ServiceReference1.GetBillResponse GetBill(demo.ServiceReference1.GetBillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBill", ReplyAction="*")]
        System.Threading.Tasks.Task<demo.ServiceReference1.GetBillResponse> GetBillAsync(demo.ServiceReference1.GetBillRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://tempuri.org/", Order=0)]
        public demo.ServiceReference1.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(demo.ServiceReference1.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlString;
        
        public GetTokenRequestBody() {
        }
        
        public GetTokenRequestBody(string xmlString) {
            this.xmlString = xmlString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public demo.ServiceReference1.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(demo.ServiceReference1.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult) {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBill", Namespace="http://tempuri.org/", Order=0)]
        public demo.ServiceReference1.GetBillRequestBody Body;
        
        public GetBillRequest() {
        }
        
        public GetBillRequest(demo.ServiceReference1.GetBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ComStr;
        
        public GetBillRequestBody() {
        }
        
        public GetBillRequestBody(string jsonString, string ComStr) {
            this.jsonString = jsonString;
            this.ComStr = ComStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillResponse", Namespace="http://tempuri.org/", Order=0)]
        public demo.ServiceReference1.GetBillResponseBody Body;
        
        public GetBillResponse() {
        }
        
        public GetBillResponse(demo.ServiceReference1.GetBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBillResult;
        
        public GetBillResponseBody() {
        }
        
        public GetBillResponseBody(string GetBillResult) {
            this.GetBillResult = GetBillResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iPaiWebServiceSoapChannel : demo.ServiceReference1.iPaiWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iPaiWebServiceSoapClient : System.ServiceModel.ClientBase<demo.ServiceReference1.iPaiWebServiceSoap>, demo.ServiceReference1.iPaiWebServiceSoap {
        
        public iPaiWebServiceSoapClient() {
        }
        
        public iPaiWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iPaiWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPaiWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPaiWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        demo.ServiceReference1.GetTokenResponse demo.ServiceReference1.iPaiWebServiceSoap.GetToken(demo.ServiceReference1.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken(string xmlString) {
            demo.ServiceReference1.GetTokenRequest inValue = new demo.ServiceReference1.GetTokenRequest();
            inValue.Body = new demo.ServiceReference1.GetTokenRequestBody();
            inValue.Body.xmlString = xmlString;
            demo.ServiceReference1.GetTokenResponse retVal = ((demo.ServiceReference1.iPaiWebServiceSoap)(this)).GetToken(inValue);
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<demo.ServiceReference1.GetTokenResponse> demo.ServiceReference1.iPaiWebServiceSoap.GetTokenAsync(demo.ServiceReference1.GetTokenRequest request) {
            return base.Channel.GetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<demo.ServiceReference1.GetTokenResponse> GetTokenAsync(string xmlString) {
            demo.ServiceReference1.GetTokenRequest inValue = new demo.ServiceReference1.GetTokenRequest();
            inValue.Body = new demo.ServiceReference1.GetTokenRequestBody();
            inValue.Body.xmlString = xmlString;
            return ((demo.ServiceReference1.iPaiWebServiceSoap)(this)).GetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        demo.ServiceReference1.GetBillResponse demo.ServiceReference1.iPaiWebServiceSoap.GetBill(demo.ServiceReference1.GetBillRequest request) {
            return base.Channel.GetBill(request);
        }
        
        public string GetBill(string jsonString, string ComStr) {
            demo.ServiceReference1.GetBillRequest inValue = new demo.ServiceReference1.GetBillRequest();
            inValue.Body = new demo.ServiceReference1.GetBillRequestBody();
            inValue.Body.jsonString = jsonString;
            inValue.Body.ComStr = ComStr;
            demo.ServiceReference1.GetBillResponse retVal = ((demo.ServiceReference1.iPaiWebServiceSoap)(this)).GetBill(inValue);
            return retVal.Body.GetBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<demo.ServiceReference1.GetBillResponse> demo.ServiceReference1.iPaiWebServiceSoap.GetBillAsync(demo.ServiceReference1.GetBillRequest request) {
            return base.Channel.GetBillAsync(request);
        }
        
        public System.Threading.Tasks.Task<demo.ServiceReference1.GetBillResponse> GetBillAsync(string jsonString, string ComStr) {
            demo.ServiceReference1.GetBillRequest inValue = new demo.ServiceReference1.GetBillRequest();
            inValue.Body = new demo.ServiceReference1.GetBillRequestBody();
            inValue.Body.jsonString = jsonString;
            inValue.Body.ComStr = ComStr;
            return ((demo.ServiceReference1.iPaiWebServiceSoap)(this)).GetBillAsync(inValue);
        }
    }
}
