//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WebApi.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TestWebServicesSoap", Namespace="http://tempuri.org/")]
    public partial class TestWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginPlayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPlayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback DepositPlayerMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback WithdrawPlayerMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBrandCompletedGameResultsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TestWebServices() {
            this.Url = global::WebApi.Properties.Settings.Default.WebApi_localhost_TestWebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginPlayerCompletedEventHandler LoginPlayerCompleted;
        
        /// <remarks/>
        public event QueryPlayerCompletedEventHandler QueryPlayerCompleted;
        
        /// <remarks/>
        public event DepositPlayerMoneyCompletedEventHandler DepositPlayerMoneyCompleted;
        
        /// <remarks/>
        public event WithdrawPlayerMoneyCompletedEventHandler WithdrawPlayerMoneyCompleted;
        
        /// <remarks/>
        public event GetBrandCompletedGameResultsCompletedEventHandler GetBrandCompletedGameResultsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginPlayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginPlayer(string Name, string PassWord, string UserHostAddress, string UserAgent) {
            object[] results = this.Invoke("LoginPlayer", new object[] {
                        Name,
                        PassWord,
                        UserHostAddress,
                        UserAgent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginPlayerAsync(string Name, string PassWord, string UserHostAddress, string UserAgent) {
            this.LoginPlayerAsync(Name, PassWord, UserHostAddress, UserAgent, null);
        }
        
        /// <remarks/>
        public void LoginPlayerAsync(string Name, string PassWord, string UserHostAddress, string UserAgent, object userState) {
            if ((this.LoginPlayerOperationCompleted == null)) {
                this.LoginPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginPlayerOperationCompleted);
            }
            this.InvokeAsync("LoginPlayer", new object[] {
                        Name,
                        PassWord,
                        UserHostAddress,
                        UserAgent}, this.LoginPlayerOperationCompleted, userState);
        }
        
        private void OnLoginPlayerOperationCompleted(object arg) {
            if ((this.LoginPlayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginPlayerCompleted(this, new LoginPlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPlayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryPlayer(string Name, string PassWord) {
            object[] results = this.Invoke("QueryPlayer", new object[] {
                        Name,
                        PassWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPlayerAsync(string Name, string PassWord) {
            this.QueryPlayerAsync(Name, PassWord, null);
        }
        
        /// <remarks/>
        public void QueryPlayerAsync(string Name, string PassWord, object userState) {
            if ((this.QueryPlayerOperationCompleted == null)) {
                this.QueryPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPlayerOperationCompleted);
            }
            this.InvokeAsync("QueryPlayer", new object[] {
                        Name,
                        PassWord}, this.QueryPlayerOperationCompleted, userState);
        }
        
        private void OnQueryPlayerOperationCompleted(object arg) {
            if ((this.QueryPlayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPlayerCompleted(this, new QueryPlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DepositPlayerMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DepositPlayerMoney(string Name, string PassWord, decimal Amount) {
            object[] results = this.Invoke("DepositPlayerMoney", new object[] {
                        Name,
                        PassWord,
                        Amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DepositPlayerMoneyAsync(string Name, string PassWord, decimal Amount) {
            this.DepositPlayerMoneyAsync(Name, PassWord, Amount, null);
        }
        
        /// <remarks/>
        public void DepositPlayerMoneyAsync(string Name, string PassWord, decimal Amount, object userState) {
            if ((this.DepositPlayerMoneyOperationCompleted == null)) {
                this.DepositPlayerMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDepositPlayerMoneyOperationCompleted);
            }
            this.InvokeAsync("DepositPlayerMoney", new object[] {
                        Name,
                        PassWord,
                        Amount}, this.DepositPlayerMoneyOperationCompleted, userState);
        }
        
        private void OnDepositPlayerMoneyOperationCompleted(object arg) {
            if ((this.DepositPlayerMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DepositPlayerMoneyCompleted(this, new DepositPlayerMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WithdrawPlayerMoney", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WithdrawPlayerMoney(string Name, string PassWord, decimal Amount) {
            object[] results = this.Invoke("WithdrawPlayerMoney", new object[] {
                        Name,
                        PassWord,
                        Amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WithdrawPlayerMoneyAsync(string Name, string PassWord, decimal Amount) {
            this.WithdrawPlayerMoneyAsync(Name, PassWord, Amount, null);
        }
        
        /// <remarks/>
        public void WithdrawPlayerMoneyAsync(string Name, string PassWord, decimal Amount, object userState) {
            if ((this.WithdrawPlayerMoneyOperationCompleted == null)) {
                this.WithdrawPlayerMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWithdrawPlayerMoneyOperationCompleted);
            }
            this.InvokeAsync("WithdrawPlayerMoney", new object[] {
                        Name,
                        PassWord,
                        Amount}, this.WithdrawPlayerMoneyOperationCompleted, userState);
        }
        
        private void OnWithdrawPlayerMoneyOperationCompleted(object arg) {
            if ((this.WithdrawPlayerMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WithdrawPlayerMoneyCompleted(this, new WithdrawPlayerMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBrandCompletedGameResults", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBrandCompletedGameResults(string starTime, string endTime) {
            object[] results = this.Invoke("GetBrandCompletedGameResults", new object[] {
                        starTime,
                        endTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBrandCompletedGameResultsAsync(string starTime, string endTime) {
            this.GetBrandCompletedGameResultsAsync(starTime, endTime, null);
        }
        
        /// <remarks/>
        public void GetBrandCompletedGameResultsAsync(string starTime, string endTime, object userState) {
            if ((this.GetBrandCompletedGameResultsOperationCompleted == null)) {
                this.GetBrandCompletedGameResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBrandCompletedGameResultsOperationCompleted);
            }
            this.InvokeAsync("GetBrandCompletedGameResults", new object[] {
                        starTime,
                        endTime}, this.GetBrandCompletedGameResultsOperationCompleted, userState);
        }
        
        private void OnGetBrandCompletedGameResultsOperationCompleted(object arg) {
            if ((this.GetBrandCompletedGameResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBrandCompletedGameResultsCompleted(this, new GetBrandCompletedGameResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LoginPlayerCompletedEventHandler(object sender, LoginPlayerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginPlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginPlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void QueryPlayerCompletedEventHandler(object sender, QueryPlayerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DepositPlayerMoneyCompletedEventHandler(object sender, DepositPlayerMoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepositPlayerMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DepositPlayerMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WithdrawPlayerMoneyCompletedEventHandler(object sender, WithdrawPlayerMoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WithdrawPlayerMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WithdrawPlayerMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetBrandCompletedGameResultsCompletedEventHandler(object sender, GetBrandCompletedGameResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBrandCompletedGameResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBrandCompletedGameResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591